Repository JuliaRobotics/Arena.jl, pull requests merged in 2019-01, with the labels that each got.

#15 Feature/graffvizualization
  README.md
  REQUIRE
  src/AnimationUtils.jl
  src/Arena.jl
  src/BigDataUtils.jl
  src/BotVis.jl
  src/CameraModel.jl
  src/ColorUtils.jl
  src/DirectorVisService.jl
  src/GeneralUtils.jl
  src/GraphVisualizationService.jl
  src/HighLevelAPI.jl
  src/ImageUtils.jl
  src/MeshUtils.jl
  src/PointClouds.jl
  src/RobotSceneModels.jl
  src/VisualizationTypes.jl
  src/VisualizationUtils.jl
  src/VisualizeLines.jl
  src/VisualizePosesPoints.jl
  src/deprecated/Deprecated.jl
  src/deprecated/DeprecatedCG.jl
  src/deprecated/DeprecatedGraff.jl
  src/plugins/GraffVisualizationService.jl
  src/plugins/ReprojectBearingRange.jl
  src/plugins/Template.jl
  src/plugins/VisualizationDefault.jl
  test/testGraff.jl
Labels: major, refactor

#16 Minor change to read in the GraffConfig
  src/HighLevelAPI.jl
Labels: graff

#17 Feature/plugins/pointclouds
  src/Arena.jl
  src/HighLevelAPI.jl
  src/ImageUtils.jl
  src/plugins/GetRobotConfiguration.jl
  src/plugins/PointClouds.jl
Labels: enhancement, plugin, pointcloud

#18 not session
  src/plugins/VisualizationDefault.jl
Labels: bug

#19 don't clear the stack trace
  src/HighLevelAPI.jl
Labels: bug, enhancement, plugin
